### ISSUE TITLE
 发送消息给undefined，提示ws-plugin出现错误 [...] message/send 请求超时, 请检查账号状态或重启QQ！

### ISSUE THREAD

**Issue by madoka315** [xiaoye12123/ws-plugin#3]
**环境**：winserver，使用的是最新TRSS-Yunzai 3.1.3版本，ws-plugin为red分支最新版本，chronocat为0.0.54(只能找到这个)，qqnt为9.9.2.16183。
**目的**：想通过插件接到chronocat-qqnt，再将消息通过插件发送给连接的[hoshinobot](https://github.com/Ice9Coffee/HoshinoBot)和[yobot](https://github.com/yuudi/yobot)（两个都是nonebot1、反向ws连接的）
**问题**：发送给hoshinobot正常，但发送给yobot时必定显示 
> ws-plugin出现错误 [...] message/send 请求超时, 请检查账号状态或重启QQ！

此时查看qqnt窗口发现消息实际已经正常触发，只是发给了`undefined`。不知道如何解决。
**相关图片**：
- ws-plugin配置
![{79928E04-708F-4666-AA6D-6C7ADD18C252}](https://picss.sunbangyan.cn/2023/11/16/a9b28deba4f5b99f0a5a8023617598bd.png)
- 发生错误时的提示
![QQ截图20231116191304](https://picst.sunbangyan.cn/2023/11/16/b6b6623cb6e3dc45dcb121ceee2dd495.png)
- 发生错误时的qqnt
- ![undefined](https://picdm.sunbangyan.cn/2023/11/16/74475b701a02294455b0f1815a1c31c0.png)

自己不太懂，不知是适配问题还是有什么弄错了，希望得到回复，万分感谢

**Comment by xiaoye12123** [comment]
已更新

**Comment by madoka315** [comment]
更新后完美解决
