### ISSUE TITLE
插件支不支持连接red？

### ISSUE THREAD

**Issue by nicklly** [xiaoye12123/ws-plugin#7]
RT
想通过trss云崽连接red（NTQQ）和onebot
可是按照下图配置 终端没反应
![Image_1701913441029](https://github.com/xiaoye12123/ws-plugin/assets/17716585/650d363f-dfe6-49b6-8bdd-ad3217ecbc4b)

**Comment by nicklly** [comment]
提一嘴.... onebot已经连接成功了

**Comment by xiaoye12123** [comment]
branch red

**Comment by Zyy955** [comment]
人才捏

**Comment by nicklly** [comment]
> branch red

ok 谢谢😊
